# Generated by Django 5.2.8 on 2025-11-20 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_registro', models.IntegerField(verbose_name='Nº Registro')),
                ('num_contrato', models.IntegerField(blank=True, null=True, verbose_name='Nº Contrato')),
                ('data_admissao', models.DateField(verbose_name='Data de Admissão/Cadastro')),
                ('situacao', models.CharField(choices=[('ATIVO', 'Ativo'), ('INATIVO', 'Inativo'), ('PENDENTE', 'Pendente')], default='ATIVO', max_length=10, verbose_name='Situação')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome Completo')),
                ('apelido', models.CharField(blank=True, max_length=100, verbose_name='Apelido / Nome Fantasia')),
                ('data_nascimento', models.DateField(verbose_name='Data de Nascimento')),
                ('cpf', models.CharField(max_length=14, verbose_name='CPF')),
                ('rg', models.CharField(max_length=20, verbose_name='RG / Inscrição Estadual')),
                ('nacionalidade', models.CharField(default='Brasileira', max_length=100)),
                ('naturalidade', models.CharField(blank=True, max_length=100, verbose_name='Naturalidade (Cidade/UF)')),
                ('estado_civil', models.CharField(choices=[('SOLTEIRO', 'Solteiro(a)'), ('CASADO', 'Casado(a)'), ('DIVORCIADO', 'Divorciado(a)'), ('VIUVO', 'Viúvo(a)'), ('UNIAO', 'União Estável')], max_length=10)),
                ('profissao', models.CharField(blank=True, max_length=100, verbose_name='Profissão')),
                ('nome_pai', models.CharField(blank=True, max_length=255, verbose_name='Nome do Pai')),
                ('nome_mae', models.CharField(blank=True, max_length=255, verbose_name='Nome da Mãe')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail')),
                ('tel_residencial', models.CharField(blank=True, max_length=20, verbose_name='Tel. Residencial')),
                ('tel_trabalho', models.CharField(blank=True, max_length=20, verbose_name='Tel. Trabalho')),
                ('celular', models.CharField(blank=True, max_length=20, verbose_name='Celular/WhatsApp')),
                ('cep', models.CharField(max_length=9, verbose_name='CEP')),
                ('endereco', models.CharField(max_length=255, verbose_name='Logradouro (Rua, Av.)')),
                ('numero', models.CharField(blank=True, max_length=20, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=100, verbose_name='Complemento')),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2, verbose_name='UF')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='fotos_cadastros/')),
                ('observacoes', models.TextField(blank=True, verbose_name='Observações')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Cadastro',
                'verbose_name_plural': 'Cadastros',
                'ordering': ['nome'],
                'unique_together': {('empresa', 'cpf'), ('empresa', 'num_contrato'), ('empresa', 'num_registro')},
            },
        ),
    ]
